config/routes.rb
Rails.application.routes.draw do
  mount Blacklight::Engine => '/'

  root to: "catalog#index", collection: 'vbl'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Create named routes for each collection specified in tabs.yml
  YAML.load_file( File.join(Rails.root, "config", "repositories.yml") )["Catalog"]["repositories"].each do |coll|
     get "#{coll[0]}" => "catalog#index", :collection => "#{coll[0]}"
  end

  scope "admin" do
    resources :records do
      patch 'upload', :on => :collection
    end
    resources :users
    delete "clear_patron_data", :to => "users#clear_patron_data"
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'login', to: redirect { |params, request| "#{Rails.application.config.relative_url_root}/users/auth/nyulibraries?#{request.query_string}" }, as: :login
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Connects this user object to Blacklights Bookmarks and Folders.
  include Blacklight::User
  # Login with NYULibraris OAuth provider
  devise :omniauthable, omniauth_providers: [:nyulibraries]

  scope :non_admin, -> { where.not(admin: true) }

  serialize :admin_collections

  acts_as_indexed fields: [:firstname, :lastname, :username, :email]

  # Create a CSV format
  comma do
    username
    firstname
    lastname
    email
  end

  def has_admin_collections?
    self.admin_collections? rescue false
  end

  def has_global_collection?
    self.admin_collections.include? "global" rescue false
  end

  # Get user collections for @user instance, cast as Array if necessary
  def user_collections
    @user_collections ||= (self.admin_collections.nil?) ? [] :
                            (self.admin_collections.is_a? Array) ?
                              self.admin_collections : [self.admin_collections]
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_filter :require_valid_omniauth, only: :nyulibraries
  def nyulibraries
    # Find existing or initialize new user,
    # and save new attributes each time
    @user = find_user_with_or_without_provider.first_or_initialize(attributes_from_omniauth)
    @user.update_attributes(attributes_from_omniauth)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      logger.info(find_message(:success, kind: "NYU Libraries"))
    else
      session["devise.nyulibraries_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def find_user_with_or_without_provider
    @find_user_with_or_without_provider ||= (find_user_with_provider.present?) ? find_user_with_provider : find_user_without_provider
  end

  def find_user_with_provider
    @find_user_with_provider ||= User.where(username: omniauth.uid, provider: omniauth.provider)
  end

  def find_user_without_provider
    @find_user_without_provider ||= User.where(username: omniauth.uid, provider: "")
  end

  def require_valid_omniauth
    head :bad_request unless valid_omniauth?
  end

  def valid_omniauth?
    omniauth.present? && omniauth.provider.to_s == 'nyulibraries'
  end

  def omniauth
    @omniauth ||= request.env["omniauth.auth"]
  end

  def omniauth_provider
    @omniauth_provider ||= omniauth.provider
  end

  def attributes_from_omniauth
    {
      provider: omniauth_provider,
      email: omniauth_email,
      firstname: omniauth_firstname,
      lastname: omniauth_lastname,
      institution_code: omniauth_institution,
      aleph_id: omniauth_aleph_id,
      patron_status: omniauth_patron_status
    }
  end

  def omniauth_email
    @omniauth_email ||= omniauth.info.email
  end

  def omniauth_firstname
    @omniauth_firstname ||= omniauth.info.first_name
  end

  def omniauth_lastname
    @omniauth_lastname ||= omniauth.info.last_name
  end

  def omniauth_institution
    @omniauth_institution ||= omniauth.extra.institution_code
  end

  def omniauth_identities
    @omniauth_identities ||= omniauth.extra.identities
  end

  def omniauth_aleph_identity
    @omniauth_aleph_identity ||= omniauth_identities.find do |omniauth_identity|
      omniauth_identity.provider == 'aleph'
    end
  end

  def omniauth_aleph_id
    unless omniauth_aleph_identity.blank?
      @omniauth_aleph_id ||= omniauth_aleph_identity.uid
    end
  end

  def omniauth_patron_status
    unless omniauth_aleph_identity.blank?
      @omniauth_patron_status ||= omniauth_aleph_identity.properties.patron_status
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json, :csv
  respond_to :js, :only => [:update]
  # Privileged controller
  before_action :authenticate_admin
  # Edit the submitted admin collections based on existing collections in @user's db entry
  before_action :update_admin_collections, :only => [:update]

  # GET /users
  def index
    @users = User.order(sort_column + " " + sort_direction).page(params[:page]).per(30)
    @users = @users.with_query(params[:q]) unless params[:q].blank?

    respond_with(@users)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])

    respond_with(@user)
  end

  # PUT /users/1
  def update
    # Update admin preferences
    @user.admin = @user.user_collections.present?
    @user.admin_collections = @user.user_collections

    flash[:notice] = t('users.update_success') if @user.save

    respond_with(@user)
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_with(@user)
  end

  # DELETE /users/clear_patron_data
  def clear_patron_data
    @users = User.all

    flash[:success] = t('users.clear_patron_data_success') if User.non_admin.destroy_all

    respond_with(@users, :location => users_url) do |format|
      format.html { redirect_to users_url }
    end
  end

  # Implement sort column for User class
  def sort_column
    super "User", "lastname"
  end
  helper_method :sort_column

end

app/views/users/_search_form.html.erb
<div>
<%= form_tag users_path, :method => :get, :class => "form-inline clearfix" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div class="input-group col-sm-8">
      <label for="q" class="sr-only">Search...</label>
      <input autofocus="autofocus" class="search_q q form-control" id="q" name="q" placeholder="Search..." type="text">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn form-control" id="search">
          <span class="submit-search-text">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
<% end %>
</div>

app/views/users/_users.html.erb
<p><%= page_entries_info @users %></p>

<%= paginate @users, theme: "bootstrap" %>

<div class="btn-group">
  <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
    Action
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to users_url(:format => :csv) do %><i class="glyphicon glyphicon-download"></i> Download as CSV<% end -%></li>
  </ul>
</div>

<div class="btn-group">
  <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
    Delete
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to clear_patron_data_url, :data => {:confirm => 'This will delete all non-admin patrons and cannot be undone. Are you sure?'}, :method => :delete do %><i class="glyphicon glyphicon-ban-circle"></i> Clear all user data<% end -%></li>
  </ul>
</div>

<br /><br />

<table class="table table-striped">
  <thead>
    <tr>
  		<th><%= sortable "username"%></th>
  		<th class="hidden-phone"><%= sortable "firstname"%></th>
  		<th class="hidden-phone"><%= sortable "lastname"%></th>
  		<th class="hidden-phone"><%= sortable "email"%></th>
  		<th class="hidden-phone">Admin?</th>
  		<th>Options</th>
    </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
  	<tr>
    	<td><%=h user.username %></td>
    	<td class="hidden-phone"><%=h user.firstname %></td>
    	<td class="hidden-phone"><%=h user.lastname %></td>
    	<td class="hidden-phone"><%=h user.email %></td>
    	<td class="hidden-phone"><%=h user.admin? %></td>
    	<td><%= link_to 'Show', user %></td>
    	<td><%= link_to_if(user.username != current_user.username, 'Destroy', user, :data => {:confirm => 'Are you sure?'}, :method => :delete) %></td>
 	  </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @users, theme: "bootstrap" %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= render "search_form" %>

<div id="users">
<%= render "users" %>
</div>

app/views/users/show.html.erb
<div id="show_user">
  <dl class="dl-horizontal">

  <dt>NetID:</dt>
  <dd>&nbsp;<%=h @user.username %></dd>

  <dt>First name:</dt>
  <dd>&nbsp;<%=h @user.firstname %></dd>

  <dt>Last name:</dt>
  <dd>&nbsp;<%=h @user.lastname %></dd>

  <dt>E-mail:</dt>
  <dd>&nbsp;<%=h @user.email %></dd>

  <dt>Admin for:</dt>
  <dd><%= form_for @user, :remote => true  do |f| %>

  <% collection_codes.each do |collection| %>
    <% if current_user_has_access_to_collection? collection %>
      <label class="checkbox">
      <%= f.check_box "umbra_admin_collections[#{collection}]",
        :value => collection,
        :checked => (collections_user_can_admin.include? collection),
        :disabled => ((current_user.username == @user.username && (!collections_user_can_admin.include? "global")) or (current_user.username == @user.username && collection == "global")) %>
      <%= collection.underscore.humanize %>
      </label>
    <% end -%>
  <% end -%>
  <button data-remote="true" type="submit" class="btn">Update</button>
  <% end %>
  </dd>

</dl>

<i class="glyphicon glyphicon-chevron-left"></i>
<%= link_to 'Back', users_path %>

</div>

app/views/users/update.js.erb
$(".flash_messages").html("<%=j render '/flash_msg'%>");