config/routes.rb
Rails.application.routes.draw do
  mount Blacklight::Engine => '/'

  root to: "catalog#index", collection: 'vbl'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  # Create named routes for each collection specified in tabs.yml
  YAML.load_file( File.join(Rails.root, "config", "repositories.yml") )["Catalog"]["repositories"].each do |coll|
     get "#{coll[0]}" => "catalog#index", :collection => "#{coll[0]}"
  end

  scope "admin" do
    resources :records do
      patch 'upload', :on => :collection
    end
    resources :users
    delete "clear_patron_data", :to => "users#clear_patron_data"
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'login', to: redirect { |params, request| "#{Rails.application.config.relative_url_root}/users/auth/nyulibraries?#{request.query_string}" }, as: :login
  end
end

app/models/umbra/record.rb
module Umbra
  class Record < ActiveRecord::Base

    # This hack forces @record instance variable routes not to prepend umbra_
    def self.model_name
      ActiveModel::Name.new("Umbra::Record", nil, "Record")
    end

    # Include facets functions here
    include Umbra::Facets

    validates_presence_of :collection, :title

    RECORD_ATTRIBUTES = [:collection, :description, :identifier, :record_attributes, :title, :original_id]

    # Facets use Dublin Core naming scheme
    add_facets :extent, :coverage_spatial, :coverage_temporal, :coverage_jurisdiction,
               :source, :language, :accrualPeriodicity, :subject_controlled, :subject_tag

    # Creat attr accessors for each facet list
    facets_accessible.each do |facet|
      RECORD_ATTRIBUTES << facet
    end

    # Make each facet set taggable
    facets_taggable.each do |facet|
      acts_as_taggable_on facet
    end

    searchable :auto_index => :index? do
      text :title, :boost => 5.0, :stored => true
      text :description, :stored => true
      text :collection, :stored => true
      string :resource_id, :stored => true do
        to_param
      end
      string :title_sort, :stored => true do
        title
      end
      string :collection, :stored => true
      string :identifier, :stored => true
      # Usee the
      facets_accessible.each do |facet|
        string facet.to_sym, :multiple => true, :stored => true
      end
    end

    # Always auto_index for now
    # Could insert logic here for when to auto_index
    def index?
      true
    end

  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # Privileged controller
  before_action :authenticate_admin
  # Convert blacnk values to nil in params when creating and updating
  before_action :blank_to_nil_params, :only => [:create, :update]
  respond_to :html, :json

  # GET /records
  # GET /records.json
  def index
    # Generate sunspot search
    @records = record_default_search

    respond_with(@records)
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Umbra::Record.find(params[:id])

    respond_with(@record)
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Umbra::Record.new
    respond_with(@record)
  end

  # GET /records/1/edit
  def edit
    @record = Umbra::Record.find(params[:id])
    respond_with(@record)
  end

  # POST /records
  # POST /records.json
  def create
    @record = Umbra::Record.new(record_params)

    flash[:notice] = t("records.create_success") if @record.save
    respond_with(@record)
  end

  # PATCH /records/1
  # PATCH /records/1.json
  def update
    @record = Umbra::Record.find(params[:id])

    flash[:notice] = t("records.update_success") if @record.update_attributes(record_params)
    respond_with(@record)
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Umbra::Record.find(params[:id])
    @record.destroy

    respond_with(@record)
  end

  # PATCH /records/update
  def upload
    @records = record_default_search
    csv_file = params[:csv]
    begin
      csv_upload = Umbra::CsvUpload.new(csv_file, current_user)
      flash[:success] = "Successfully loaded CSV records into database. Reindexing will take a moment." if csv_upload.upload
    rescue ArgumentError => e
      flash[:error] = e.message
    end

    respond_with(@records) do |format|
      format.html { render :index }
    end
  end

  # Implement sort column function foar Record class
  def sort_column
    super "Umbra::Record", "title_sort"
  end
  helper_method :sort_column

  # Convert blank values to nil values in params
  # Blacklight prints an empty "Field name:" label if the value is blank so this makes sure the values are nil
  def blank_to_nil_params
    record_params.merge!(record_params){|k, v| v.blank? ? nil : v}
  end
  private :blank_to_nil_params

  def record_params
    params.require(:record).permit(*Umbra::Record::RECORD_ATTRIBUTES)
  end
  private :record_params

  # Default admin search in Sunspot
  def record_default_search
    Umbra::Record.search {
      fulltext params[:q]
      any_of do
        current_user_admin_collections.each { |collection|
          with(:collection, collection)
        }
      end
      order_by(sort_column.to_sym, sort_direction.to_sym)
      paginate :page => params[:page] || 1, :per_page => 30
    }
  end
  private :record_default_search
end

app/helpers/record_helper.rb
module RecordHelper
  
  #
  # Return sorted list of facets
  #
  
  def subject_controlled_list
    @subject_controlled_list ||= Umbra::Record.subject_controlled_counts.sort_by(&:name)
  end
  
  def extent_list
    @extent_list ||= Umbra::Record.extent_counts.sort_by(&:name)
  end
  
  def coverage_spatial_list
    @coverage_spatial_list ||= Umbra::Record.coverage_spatial_counts.sort_by(&:name)
  end
  
  def coverage_temporal_list
    @coverage_temporal_list ||= Umbra::Record.coverage_temporal_counts.sort_by(&:name)
  end
  
  def coverage_jurisdiction_list
    @coverage_jurisdiction_list ||= Umbra::Record.coverage_jurisdiction_counts.sort_by(&:name)
  end
  
  def source_list
    @source_list ||= Umbra::Record.source_counts.sort_by(&:name)
  end
  
  def language_list
    @language_list ||= Umbra::Record.language_counts.sort_by(&:name)
  end
  
  def accrualPeriodicity_list
    @accrualPeriodicity_list ||= Umbra::Record.accrualPeriodicity_counts.sort_by(&:name)
  end
  
  def subject_tag_list
    @subject_tag_list ||= Umbra::Record.subject_tag_counts.sort_by(&:name)
  end

end

app/views/records/_form.html.erb
<% record_help = t("blacklight.create_record_help") %>

<%= form_for @record do |f| %>

  <% if @record.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>
      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
      <div class="form-group">
        <%= f.label :collection %>
        <%= f.text_field :collection, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :identifier %>
        <%= f.text_field :identifier , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, :rows => 10 , class: "form-control" %>
      </div>
  </fieldset>
  <fieldset>
    <legend>Facets</legend>
    <span class="help-block"><%= t("blacklight.create_record_help")%></span>
      <div class="form-group">
        <%= f.label :subject_controlled_list, "Categories" %>
        <%= f.text_field :subject_controlled_list, :placeholder => "dc.subject.controlled" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :source_list, "Databases" %>
        <%= f.text_field :source_list, :placeholder => "dc.source" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :extent_list, "Extent" %>
        <%= f.text_field :extent_list, :placeholder => "dc.extent" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :language_list, "Languages" %>
        <%= f.text_field :language_list, :placeholder => "dc.language" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :coverage_spatial_list, "Locations" %>
        <%= f.text_field :coverage_spatial_list, :placeholder => "dc.coverage.spatial" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :accrualPeriodicity_list, "Frequency" %>
        <%= f.text_field :accrualPeriodicity_list, :placeholder => "dc.accrualPeriodicity" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :coverage_temporal_list, "Activity" %>
        <%= f.text_field :coverage_temporal_list, :placeholder => "dc.coverage.temporal" , class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :subject_tag_list, "Tags" %>
        <%= f.text_field :subject_tag_list, :placeholder => "dc.subject.tag" , class: "form-control" %>
      </div>
  </fieldset>

  <div class="actions">
    <button type="submit" class="btn btn-default">Save changes</button>
  </div>
<% end %>

app/views/records/_search_form.html.erb
<div>
<%= form_tag records_path, :method => :get, :class => "form-inline clearfix" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div class="input-group col-sm-8">
      <label for="q" class="sr-only">Search...</label>
      <input autofocus="autofocus" class="search_q q form-control" id="q" name="q" placeholder="Search..." type="text">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn form-control" id="search">
          <span class="submit-search-text">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
<% end %>
</div>

app/views/records/_upload.html.erb
<% if delayed_jobs_running? %>
<h2>Uploading CSV file. Refresh periodically.</h2>
<div class="progress progress-striped active" style="width: 50%">
  <div class="bar" style="width: 100%;"></div>
</div>
<% end %>

<%= form_tag({:action => :upload}, :multipart => true, :class => "form-upload well well-sm") do %>
  <h5>Batch upload records from CSV file</h5>
  <%= file_field_tag 'csv', :size => 10 %><br />
  <button type="submit" class="btn btn-default">
    <i class="glyphicon glyphicon-upload"></i> Upload
  </button>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<br />

<%= link_to @record, class: "btn btn-link" do %>
  <i class="glyphicon glyphicon-search"></i> Edit
<% end %>
<%= link_to records_path, class: "btn btn-link" do %>
  <i class="glyphicon glyphicon-chevron-left"></i> Back
<% end %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<%= render 'search_form' %>
<%= render 'upload' %>

<p><%= page_entries_info_sunspot @records %></p>

<%= paginate @records.hits, :theme => "bootstrap" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "collection" %></th>
      <th><%= sortable "title_sort", "Title" %></th>
      <th class="hidden-phone">Identifier</th>
      <th class="hidden-phone">Description</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
<% @records.results.each do |record| %>
    <tr>
      <td><%= record.collection %></td>
      <td><%= record.title %></td>
      <td class="hidden-phone"><%= link_to_unless(record.identifier.nil?, truncate(record.identifier, :length => 25), record.identifier, :title => record.identifier, :alt => record.identifier) %></td>
      <td class="hidden-phone"><%= truncate(record.description, :length => 140) %></td>
      <td><%= link_to 'Show', record %></td>
      <td><%= link_to 'Edit', edit_record_path(record) %></td>
      <td><%= link_to 'Destroy', record, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= paginate @records.hits, :theme => "bootstrap"  %>

<br />

<%= link_to new_record_path, class: "btn btn-default" do %>
  <i class="glyphicon glyphicon-plus"></i> New Record
<% end %>

app/views/records/new.html.erb
<h1>New record</h1>

<div class="clearfix">
<%= render 'form' %>
</div>
<br />

<i class="glyphicon glyphicon-chevron-left"></i><%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<h1><%= @record.collection %>: <%= @record.title %></h1>

<dl class="dl-horizontal">

  <dt>Collection:
  <dd>&nbsp;<%= @record.collection %></dd>

  <dt>Title:</dt>
  <dd>&nbsp;<%= @record.title %></dd>

  <dt>Identifier:</dt>
  <dd>&nbsp;<%= @record.identifier %></dd>

  <dt>Description:</dt>
  <dd>&nbsp;<%= @record.description %></dd>

</dl>

<%= link_to edit_record_path(@record), class: "btn btn-link" do %>
  <i class="glyphicon glyphicon-wrench"></i> Edit
<% end %>
<%= link_to records_path, class: "btn btn-link" do %>
  <i class="glyphicon glyphicon-chevron-left"></i> Back
<% end %>